-- 코드를 입력하세요
SELECT A.AUTHOR_ID,
 (SELECT AUTHOR_NAME FROM AUTHOR WHERE AUTHOR_ID=A.AUTHOR_ID) AS AUTHOR_NAME,
 A.CATEGORY, A.TOTAL_SALES
 FROM
(
    SELECT AUTHOR_ID, CATEGORY, SUM(TOTAL_SALES) AS TOTAL_SALES 
    FROM (
        SELECT A.AUTHOR_ID,A.CATEGORY, A.PRICE * B.SALES AS TOTAL_SALES 
        FROM BOOK A
        JOIN (SELECT BOOK_ID, SUM(SALES) AS SALES
              FROM BOOK_SALES WHERE TO_CHAR(SALES_DATE,'YYYYMM') = '202201'
              GROUP BY BOOK_ID) B
        ON A.BOOK_ID = B.BOOK_ID
        )
    GROUP BY AUTHOR_ID, CATEGORY
) A
ORDER BY A.AUTHOR_ID, A.CATEGORY DESC
