
SELECT CAR_ID, CAR_TYPE, FEE FROM (
    SELECT A.CAR_ID, A.CAR_TYPE
        ,A.DAILY_FEE * 30 * (1-NVL(C.DISCOUNT_RATE,0)/100) AS FEE
    FROM (SELECT * FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE IN ('세단','SUV')) A 
    LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C 
    ON A.CAR_TYPE = C.CAR_TYPE
    AND C.DURATION_TYPE = '30일 이상'
) 
WHERE CAR_ID NOT IN (
      SELECT DISTINCT CAR_ID 
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE TO_CHAR(START_DATE,'YYYYMM')<='202211' AND TO_CHAR(END_DATE,'YYYYMM')>='202211'
)
AND FEE BETWEEN 500000 AND 1999999
GROUP BY CAR_ID, CAR_TYPE, FEE
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC 


    
