--  생산일자 = 2022년 5월
SELECT PRODUCT_ID, PRODUCT_NAME, TOTAL_SALES FROM (
    SELECT A.PRODUCT_ID, A.PRODUCT_NAME, SUM(A.PRICE * B.AMOUNT) AS TOTAL_SALES
    FROM FOOD_PRODUCT A JOIN FOOD_ORDER B
    ON A.PRODUCT_ID = B.PRODUCT_ID
    AND TO_CHAR(B.PRODUCE_DATE,'YYYYMM') = '202205'
    GROUP BY A.PRODUCT_ID, A.PRODUCT_NAME
) 
ORDER BY TOTAL_SALES DESC, PRODUCT_ID