-- CAR_TYPE = '트럭' 인 자동차의 대여기록에 대해 대여 기록별 대여금액 
-- DAILY_FEE * (END_DATE - START_DATE) * (1-DISCOUNT_RATE/100) 
-- SELECT A.DAILY_FEE , B.END_DATE , B.START_DATE 
-- FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
-- ON A.CAR_ID = B.CAR_ID 
-- AND A.CAR_TYPE = '트럭'


      
SELECT HISTORY_ID, FEE FROM
(SELECT B.HISTORY_ID ,A.DAILY_FEE * (B.END_DATE - B.START_DATE + 1) * (1-NVL(C.DISCOUNT_RATE,0)/100) AS FEE
 
 FROM (SELECT CAR_ID, CAR_TYPE, DAILY_FEE FROM CAR_RENTAL_COMPANY_CAR
        WHERE CAR_TYPE = '트럭') A 
 JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
 ON A.CAR_ID = B.CAR_ID
 LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
 ON A.CAR_TYPE = C.CAR_TYPE
 AND C.DURATION_TYPE = CASE WHEN B.END_DATE - B.START_DATE + 1 BETWEEN 7 AND 29 THEN '7일 이상'
                             WHEN B.END_DATE - B.START_DATE + 1 BETWEEN 30 AND 89 THEN '30일 이상'
                             WHEN B.END_DATE - B.START_DATE + 1 >= 90 THEN '90일 이상'
                            END
)
ORDER BY FEE DESC, HISTORY_ID DESC 