-- VIEWS가 가장 높은 중고거래 게시물에 대한 첨부파일 경로 
-- 경로 = /home/grep/src/BOARD_ID/FILE_ID+FILE_NAME+FILE_EXT
SELECT 
'/home/grep/src/'||B.BOARD_ID||'/'|| B.FILE_ID||B.FILE_NAME||B.FILE_EXT AS FILE_PATH
FROM USED_GOODS_BOARD A JOIN USED_GOODS_FILE B
ON A.BOARD_ID = B.BOARD_ID
WHERE A.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY B.FILE_ID DESC

